[pytest]
# Define a pasta padrão onde o pytest vai procurar os testes
testpaths = tests

# Configura a geração automática do relatório HTML sempre que rodar os testes
addopts = -v --self-contained-html

