name: Suíte de Testes Automatizados

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  testar_aplicacao:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Tesseract OCR no Servidor
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Instalar dependências do projeto
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html

    - name: Executar Suíte de Testes
      run: |
        python -m pytest

    - name: Salvar Relatório HTML como Artefato
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: relatorio-testes-html
        path: relatorios/

        - name: Executar Suíte de Testes
      env:
        JWT_SECRET_KEY: "chave-falsa-apenas-para-ci"
      run: |
        python -m pytest