name: "Pipeline de Testes Automatizados (Pytest)"

on:
  push:
    branches: [ "master", "main" ]
  schedule:
    - cron: '0 */12 * * *'

jobs:
  executar-testes:
    name: "Executar Testes Unitários e de Isolamento"
    runs-on: ubuntu-latest
    # ... resto do código

    steps:
    - name: Copiar código do repositório
      uses: actions/checkout@v4

    - name: Configurar ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar a suíte de testes com Pytest
      run: |
        pytest -v
